INSERT INTO flights (id, flight_number, origin, destination, departure_time, status, gate) VALUES
('f-1', 'LX2711', 'ZRH', 'CDG', TIMESTAMPADD(MINUTE,  30, CURRENT_TIMESTAMP), 'SCHEDULED', 'A1'),
('f-2', 'LX0318', 'ZRH', 'LHR', TIMESTAMPADD(MINUTE,  75, CURRENT_TIMESTAMP), 'SCHEDULED', 'A2'),
('f-3', 'LX1108', 'ZRH', 'BCN', TIMESTAMPADD(MINUTE, 150, CURRENT_TIMESTAMP), 'DELAYED',   'B1'),
('f-4', 'LX2711', 'ZRH', 'CDG', DATEADD('DAY',1, CURRENT_DATE) || ' 10:00:00', 'SCHEDULED', 'A1'),

('f-5', 'LX0162', 'ZRH', 'FRA', TIMESTAMPADD(MINUTE,  45, CURRENT_TIMESTAMP), 'BOARDING', 'A3'),
('f-6', 'LX1345', 'ZRH', 'MUC', TIMESTAMPADD(MINUTE,  90, CURRENT_TIMESTAMP), 'SCHEDULED', 'A4'),
('f-7', 'LX0789', 'ZRH', 'AMS', TIMESTAMPADD(MINUTE, 120, CURRENT_TIMESTAMP), 'DELAYED', 'B2'),
('f-8', 'LX1567', 'ZRH', 'VIE', TIMESTAMPADD(MINUTE, 180, CURRENT_TIMESTAMP), 'SCHEDULED', 'B3'),
('f-9', 'LX0923', 'ZRH', 'FCO', TIMESTAMPADD(MINUTE, 210, CURRENT_TIMESTAMP), 'SCHEDULED', 'A5'),
('f-10', 'LX2456', 'ZRH', 'MAD', TIMESTAMPADD(MINUTE, 240, CURRENT_TIMESTAMP), 'DELAYED', 'B4'),

('f-11', 'LX1234', 'ZRH', 'LIS', DATEADD('DAY',1, CURRENT_DATE) || ' 08:15:00', 'SCHEDULED', 'A6'),
('f-12', 'LX0318', 'ZRH', 'LHR', DATEADD('DAY',1, CURRENT_DATE) || ' 09:30:00', 'SCHEDULED', 'A2'),
('f-13', 'LX1567', 'ZRH', 'VIE', DATEADD('DAY',1, CURRENT_DATE) || ' 11:45:00', 'SCHEDULED', 'B3');
